[package]
name = "zc"
version = "0.9.3"
authors = ["Manoel de Souza <manoel.desouza@outlook.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99.0"
